### ISSUE TITLE
随便吐槽一下

### ISSUE THREAD

**Issue by hr567** [TooYoungTooSimp/seat#1]
你的代码的缩进是什么鬼？
然后我的代码长度非常的科学，并没有什么问题呀……

**Comment by TooYoungTooSimp** [comment]
这个东西是用我的路由器提交的，代码缩进被vim弄坏了。粘贴进去就变成这样了，马上将会被格式化。

**Comment by TooYoungTooSimp** [comment]
格式化完了，正准备添加新功能
